// G3: codegen — derive the system-skill allowlist from the canonical disk
// source of truth at `services/agents/skills/<slug>/`. Writes
// `src/lib/system-skills.generated.ts`. Runs in `predev` + `prebuild` so
// it stays in sync without a runtime fs read (Vercel serverless friendly).
//
// Filter rule: skip directories starting with `_` or `.` (e.g. `_deep-read`,
// `__pycache__`, `.DS_Store`).

import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(__dirname, "..", "..", "..");
const skillsDir = path.join(repoRoot, "services", "agents", "skills");
const outFile = path.join(
  __dirname,
  "..",
  "src",
  "lib",
  "system-skills.generated.ts",
);

function readSlugs(): string[] {
  if (!fs.existsSync(skillsDir)) {
    throw new Error(`gen-system-skills: skills dir not found at ${skillsDir}`);
  }
  return fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((n) => !n.startsWith("_") && !n.startsWith("."))
    .sort();
}

function main() {
  const slugs = readSlugs();
  const body = `// AUTO-GENERATED by scripts/gen-system-skills.ts. Do not edit by hand.
// Source of truth: services/agents/skills/<slug>/ (skips _-/.-prefixed dirs).
// Re-run via \`pnpm gen:system-skills\` or implicitly via predev/prebuild.

export const SYSTEM_SKILL_SLUGS: ReadonlySet<string> = new Set([
${slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
]);
`;
  fs.writeFileSync(outFile, body);
  console.log(`gen-system-skills: wrote ${slugs.length} slugs → ${outFile}`);
}

main();
