// Derive a friendly library label.
//
// Preference order (D4):
//   1. `firstname` column — explicitly captured at signup. Authoritative.
//   2. First whitespace-separated token of `name` — legacy behavior, still
//      used for anonymous users (display name auto-generated by better-auth)
//      and any pre-D4 row that never got a firstname backfilled.
//   3. "My Library" — for genuinely empty inputs.
export function deriveLibraryName(user: {
  name?: string | null;
  firstname?: string | null;
}): string {
  const firstname =
    typeof user.firstname === "string" ? user.firstname.trim() : "";
  if (firstname) return `${firstname}'s Library`;

  const raw = typeof user.name === "string" ? user.name.trim() : "";
  if (!raw) return "My Library";
  const first = raw.split(/\s+/)[0];
  if (!first) return "My Library";
  return `${first}'s Library`;
}
