// AUTO-GENERATED by scripts/gen-system-skills.ts. Do not edit by hand.
// Source of truth: services/agents/skills/<slug>/ (skips _-/.-prefixed dirs).
// Re-run via `pnpm gen:system-skills` or implicitly via predev/prebuild.

export const SYSTEM_SKILL_SLUGS: ReadonlySet<string> = new Set([
  "claim-verify",
  "data-extract",
  "deep-read",
  "lit-triage",
  "paper-search",
  "synthesis",
]);
